
- name: Do everything
  hosts: camper
  become: true
  vars_prompt:
    - name: accesspoint_wpa_passphrase
      prompt: "Enter the WPA passphrase to be set"
  roles: 
    - base
    - acable
    - bluetooth_sink
    - accesspoint
    - uplink
    - mpd
    - usbmount
