---

- name: Run the base role on all hosts
  hosts: all
  become: true
  roles:
    - base

- name: Bluetooth sinks Amsel
  hosts: bluetooth_sinks_amsel
  become: true
  roles:
    - bluetoothd
    - bluealsa
    - a2dp_agent

- name: Snapclients Amsel
  hosts: snapclients_amsel
  become: true
  roles:
    - snapclient

- name: Acables Amsel
  hosts: acables_amsel
  become: true
  roles:
    - acable

- name: Acables Bluetooth Only Amsel
  hosts: acables_bluetooth_only_amsel
  become: true
  roles:
    - acable

- name: Acables Snapserver Amsel
  hosts: acables_snapserver_amsel
  become: true
  roles:
    - acable

- name: Snapservers Amsel
  hosts: snapservers_amsel
  become: true
  roles:
    - snapserver
    - snd_aloop

- name: MPD Servers Amsel
  hosts: mpdservers_amsel
  become: true
  roles:
    - mpd

#- name: Snapservers
#  hosts: snapservers
#  become: true
#  roles:
#    - snapserver

#- name: acables
#  hosts: acables
#  become: true
#  roles:
#    - acable

#- name: Loopback module
#  hosts: snd_aloop
#  become: true
#  roles:
#    - snd_aloop
