---

### Amsel concept
### * all hosts get "base" and "snapclient"
### * If you have hardware inputs, you need "acable" to connect these inputs. If one
###   the inputs is a bluetooth input, you need "bluetooth_sink"
### * If you want a snapserver (to actually distribute audio), you need snd_aloop,
###   snapserver/snapweb and mpd

### base/snapclient 

#- name: Run base and snapclient role on all hosts
#  hosts: amsel_all
#  become: true
#  roles:
#    - base
#    - snapclient

# Warning: bluetooth_sink must be run AFTER the acable role, as it 
# uses the variable acable_config that is built in the acable role only.
- name: Configure audio connections
  hosts: amsel_adc_aloop:amsel_adc_dac:amsel_bluetooth_aloop:amsel_bluetooth_dac
  become: true
  roles:
    - acable
    - bluetooth_sink
    
#- name: Configure audio server 
#  hosts: amsel_server
#  become: true
#    - snd_aloop
#    - snapserver
#    - snapweb
#    - mpd
