---

### Amsel concept
### * all hosts get base and snapclient, both don't need an acable config
### * create a specific host group for every config that needs at least one acable and put 
###   every host in exactly one of these groups if anything more than the default is needed.
###   You can add
###   * snd_aloop 
###     enables to use Loopback dmix/dsnoop ALSA devices for audio stream mix in/fan out
###   * bluetooth_sink
###     enables acables to get audio from bluetooth
###   * snapserver
###     enables a snapserver. Needs matching snapclients to actually hear something.
###   * snapweb
###     enables snapserver to show minimal website at port :1780 to control the individual
###     snap volumes and change the snap grouping
###   * mpd
###     to listen to your local music and internet radio stations. 

### base/snapclient 

- name: Run base and snapclient role on all hosts
  hosts: amsel_all
  become: true
  roles:
    - base
    - snapclient

### various host groups with acables, use only one of them per host!

- name: Amsel snapserver/mpd host with analog and bluetooth input
  hosts: amsel_acables_bluetooth_analog_snapserver_mpd
  become: true
  roles:
    - acable
    - bluetooth_sink
    - snd_aloop
    - snapserver
    - snapweb
    - mpd
   

- name: Amsel snapserver/mpd host with analog input
  hosts: amsel_acables_analog_snapserver_mpd
  become: true
  roles:
    - acable
    - snd_aloop
    - snapserver
    - snapweb
    - mpd

- name: Amsel bluetooth and analog input
  hosts: amsel_acables_bluetooth_analog
  become: true
  roles:
    - acable
    - bluetooth_sink

- name: Amsel bluetooth input
  hosts: amsel_acables_bluetooth
  become: true
  roles:
    - acable
    - bluetooth_sink

