---

### Amsel concept
### * all hosts get base and snapclient, both don't need an acable config
### * create a specific host group for every config that needs at least one acable 
###   and put every host in exactly one of these groups if anything more than the
###   default is needed:
###   * want to have snd_aloop ? 
###     enables to use Loopback dmix/dsnoop ALSA devices for audio stream mix in/fan out
###   * want to process sound from a bluetooth and/or analog audio source? 
###     * need bluetooth_sink
###   * want to have snapserver? 
###   * want to have mpd?
### * need an snd_aloop device to mix in/fan out via a Loopback dmix/dsnoop?

### base/snapclient 

- name: Run base and snapclient role on all hosts
  hosts: all
  become: true
  roles:
    - base
    - snapclient

### various host groups with acables, use only one of them per host!

- name: Amsel snapserver/mpd host with analog and bluetooth input
  hosts: amsel_acables_bluetooth_analog_snapserver_mpd
  become: true
  roles:
    - acable
    - bluetooth_sink
    - snd_aloop
    - snapserver
    - mpd

- name: Amsel snapserver/mpd host with analog input
  hosts: amsel_acables_analog_snapserver_mpd
  become: true
  roles:
    - acable
    - snd_aloop
    - snapserver
    - mpd

- name: Amsel bluetooth and analog input
  hosts: amsel_acables_bluetooth_analog
  become: true
  roles:
    - acable
    - bluetooth_sink

- name: Amsel bluetooth input
  hosts: amsel_acables_bluetooth
  become: true
  roles:
    - acable
    - bluetooth_sink

