---

### Amsel concept
### * all hosts get "base" and "snapclient"
### * "acable" is used to create internal audio connections (similar to alsaloop),
###   "bluetooth_sink" adds the bluetooth infrastructure - but only if at least
###   one bluetooth connection is defined in acable_config.
### * "bluetooth_disable" should be executed for all hosts without any acable
###    configured if you want to be sure that bluetooth is actually switched off.
### * At least one audio server (snapserver) should be defined to actually distribute
###   audio). This needs snd_aloop, snapserver (plus snapweb when snapserver from
###   bullseye is used). And at least one of mpd and raspotify.

### base/snapclient

- name: Run base and snapclient role on all hosts
  hosts: amsel_all
  become: true
  roles:
    - base
    - snapclient
  tags: feature::base

# Warning: bluetooth_sink must be run AFTER the acable role, as it
# uses the variable acable_config that is built in the acable role only.

- name: Configure audio connections
  hosts: amsel_adc_aloop:amsel_adc_dac:amsel_bluetooth_aloop:amsel_bluetooth_dac
  become: true
  roles:
    - acable
    - bluetooth_sink
  tags: feature::acable

- name: Disable bluetooth as no acable is defined
  hosts: amsel_all:!amsel_adc_aloop:!amsel_adc_dac:!amsel_bluetooth_aloop:!amsel_bluetooth_dac
  become: true
  roles:
    - bluetooth_disable
  tags: feature::acable

- name: Configure small audio server (only snapserver)
  hosts: amsel_small_server
  become: true
  roles:
    - snd_aloop
    - snapserver
  tags: feature::small_server

- name: Configure full audio server (including mpd, raspotify)
  hosts: amsel_server
  become: true
  roles:
    - snd_aloop
    - snapserver
    - mpd
    - rompr
    - ampd
    - mpdutils
    - raspotify
  tags: feature::server
