---

- name: Run the base role on all hosts
  hosts: all
  become: true
  roles:
    - base

- name: Bluetooth sinks Amsel
  hosts: bluetooth_sinks_amsel
  become: true
  roles:
    - bluetoothd
    - bluealsa
    - a2dp_agent

- name: Snapclients Amsel
  hosts: snapclients_amsel
  become: true
  roles:
    - snapclient

- name: Acables Amsel
  hosts: acables_amsel
  become: true
  roles:
    - acable

#- name: Snapservers
#  hosts: snapservers
#  become: true
#  roles:
#    - snapserver

#- name: acables
#  hosts: acables
#  become: true
#  roles:
#    - acable

#- name: Loopback module
#  hosts: snd_aloop
#  become: true
#  roles:
#    - snd_aloop
