---

- name: Exit play if os_family is not Debian
  ansible.builtin.fail:
    msg: "ERROR: os_family of host {{ inventory_hostname }} is not Debian"
  when: ansible_facts['os_family'] != "Debian"

- name: Load the snd_aloop kernel module
  community.general.modprobe:
    name: snd_aloop
    state: present
  notify: Restart snapserver

- name: Load the snd_aloop kernel module at boot
  ansible.builtin.lineinfile:
    path: /etc/modules
    state: present
    line: snd_aloop
