---

- name: Restart acables
  ansible.builtin.systemd:
    name: "acable@{{ item.name }}.service"
    daemon_reload: yes
    state: restarted
  loop: "{{ acable_config }}"
  loop_control:
    label: "{{ item.name }}"
