---

- name: Exit play if os_family is not Debian
  ansible.builtin.fail:
    msg: "ERROR: os_family of host {{ inventory_hostname }} is not Debian"
  when: ansible_facts['os_family'] != "Debian"

- name: Install snapclient package
  ansible.builtin.apt:
    name: snapclient
    state: latest
    update_cache: yes

- name: Install snapclient config
  ansible.builtin.template:
    src: templates/etc/default/snapclient.j2
    dest: /etc/default/snapclient
    backup: yes
  notify:
    - Restart snapclient

- name: Enable snapclient to start on boot
  ansible.builtin.systemd:
    name: snapclient
    enabled: yes
