---

- name: Exit play if os_family is not Debian
  ansible.builtin.fail:
    msg: "ERROR: os_family of host {{ inventory_hostname }} is not Debian"
  when: ansible_facts['os_family'] != "Debian"

- name: Install avahi workaround
  ansible.builtin.template:
    src: templates/etc/avahi/services/spotify-connect.service
    dest: /etc/avahi/services/spotify-connect.service
  notify: "Restart avahi-daemon"

- name: Install raspotify 
  include_role: 
    name: t2d.raspotify

- name: Configure raspotify
  ansible.builtin.template:
    src: templates/etc/raspotify/conf.j2
    dest: /etc/raspotify/conf
    backup: yes
  notify: "Restart raspotify"

