---

- name: Exit play if os_family is not Debian
  ansible.builtin.fail:
    msg: "ERROR: os_family of host {{ inventory_hostname }} is not Debian"
  when: ansible_facts['os_family'] != "Debian"

- name: Install mpc for playlistbot
  ansible.builtin.apt:
    name: mpc
    state: latest
    update_cache: yes

- name: Configure playlistbot
  ansible.builtin.template:
    src: templates/etc/default/playlistbot.j2
    dest: /etc/default/playlistbot
    backup: no

- name: Create playlistbot script
  ansible.builtin.copy:
    src: files/usr/local/bin/playlistbot.sh
    dest: /usr/local/bin/playlistbot.sh
    mode: "755"

- name: Create playlistbot oneshot service
  ansible.builtin.template:
    src: templates/etc/systemd/system/playlistbot.service.j2
    dest: /etc/systemd/system/playlistbot.service
    backup: no
  notify: Restart playlistbot

- name: Create playlistbot timer
  ansible.builtin.template:
    src: templates/etc/systemd/system/playlistbot.timer.j2
    dest: /etc/systemd/system/playlistbot.timer
    backup: no
  notify: Restart playlistbot

- name: Start and enable playlistbot
  ansible.builtin.systemd:
    name: "playlistbot.timer"
    enabled: yes
    daemon_reload: yes
    state: started
  ignore_errors: "{{ ansible_check_mode }}"
