---

audio_rate: 44100
audio_format: S16_LE

snapclient_snapserver: pi2
snapclient_sink: dmix:CARD=sndrpihifiberry

snapserver_name: alsamischpult
snapserver_sourcetype: alsa
snapserver_alsadevice: dsnoop:CARD=Loopback,DEV=1
snapserver_sampleformat: "44100:16:2"
snapserver_codec: flac
snapserver_buffer: 200

aloopplay_sources:
  - hifiberry
  - CODEC
  - bluealsa
