---

snapclient_config:
  - name: spielen
    snapclient_snapserver: spielen.iselin.net
    snapclient_sink: dmix:CARD=sndrpihifiberry,DEV=0
  - name: wohnen
    snapclient_snapserver: wohnen.iselin.net
    snapclient_sink: dmix:CARD=sndrpihifiberry,DEV=0

