---

snapclient_config:
  - name: spielen
    snapclient_snapserver: spielen.iselin.net
    snapclient_sink: dmix:CARD=sndrpihifiberry,DEV=0
  - name: wohnen
    snapclient_snapserver: wohnen.iselin.net
    snapclient_sink: dmix:CARD=sndrpihifiberry,DEV=0
#  - name: pi4dev
#    snapclient_snapserver: pi4dev.iselin.net
#    snapclient_sink: dmix:CARD=sndrpihifiberry,DEV=0
