---

- name: Restart snapclients
  ansible.builtin.systemd:
    name: "snapclient@{{ item.name }}.service"
    daemon_reload: yes
    state: restarted
  loop: "{{ snapclient_config }}"
  loop_control:
    label: "{{ item.name }}"
